blank_issues_enabled: true
contact_links:
  - name: Questions and General Discussion
    url: https://github.com/MoonshotAI/kimi-cli/discussions
    about: Have questions? Welcome to open a discussion!
